sudo: required
language: ruby
services:
  - docker
env:
  - RUBY_VER=2.6.0-preview2 REDMINE_VER=master
  - RUBY_VER=2.6.0-preview2 REDMINE_VER=3.4-stable
  - RUBY_VER=2.5 REDMINE_VER=master
  - RUBY_VER=2.5 REDMINE_VER=3.4-stable
  - RUBY_VER=2.4 REDMINE_VER=master
  - RUBY_VER=2.4 REDMINE_VER=3.4-stable
  - RUBY_VER=2.3 REDMINE_VER=master
  - RUBY_VER=2.3 REDMINE_VER=3.4-stable
  - RUBY_VER=2.3 REDMINE_VER=3.3-stable
before_install:
  - docker build -t sho-h/redmine_audit:${RUBY_VER} --build-arg RUBY_VER=${RUBY_VER} --file=Dockerfile.travis .
script:
  # - bundle exec rake test
  - docker run -e REDMINE_VER=${REDMINE_VER} -e BRANCH=$(git rev-parse --abbrev-ref HEAD) sho-h/redmine_audit:${RUBY_VER}
notifications:
  email:
    recipients:
      - sho.hsmt@gmail.com
    on_success: never
    on_failure: always
